# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CITtaQzYS7rm6ZUcDmh6ClxcavH-ooEK
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install streamlit pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import tensorflow as tf
# import numpy as np
# from PIL import Image
# 
# MODEL_PATH_CNN = "/content/drive/MyDrive/Brain Tumor/models/custom_cnn_model.keras"
# IMG_SIZE = (224, 224)
# 
# CLASS_NAMES = ["glioma", "meningioma", "no_tumor", "pituitary"]
# 
# # Load CNN Model
# @st.cache_resource
# def load_cnn():
#     return tf.keras.models.load_model(MODEL_PATH_CNN)
# 
# # Image Preprocessing
# def preprocess_image(img):
#     img = img.resize(IMG_SIZE)
#     img = np.array(img) / 255.0
#     img = np.expand_dims(img, axis=0)
#     return img
# 
# # Predict Function
# def predict(model, img):
#     preds = model.predict(img)
#     class_id = np.argmax(preds)
#     confidence = float(np.max(preds))
#     return class_id, confidence, preds[0]
# 
# # Streamlit Code
# st.title("Brain Tumor Classification")
# 
# uploaded_file = st.file_uploader("Upload Brain MRI Image", type=["jpg", "jpeg", "png"])
# 
# if uploaded_file:
#     image = Image.open(uploaded_file).convert("RGB")
#     st.image(image, caption="Uploaded MRI Image", width=300)
# 
#     # Preprocess
#     img_array = preprocess_image(image)
# 
#     # Load model once
#     model = load_cnn()
# 
#     # Predict button
#     if st.button("Predict Tumor Type"):
#         class_id, conf, all_probs = predict(model, img_array)
# 
#         st.subheader(f"Prediction: **{CLASS_NAMES[class_id].upper()}**")
#         st.write(f"Confidence: **{conf*100:.2f}%**")
#

from pyngrok import ngrok

ngrok.set_auth_token("35kQh7aX3KBsNFNSAtS13tavBwl_4qYUKAPGTL5Tcd8ACzjLF")

!nohup streamlit run app.py --server.port 8501 &>/dev/null &

from pyngrok import ngrok

# Kill all tunnels
ngrok.kill()

print("All existing ngrok tunnels closed.")

public_url = ngrok.connect(8501)
public_url