# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/141Fa-J3LVKrqMMTwEMJYxePBsgA4Bb-k
"""
# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
import streamlit as st
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.image import img_to_array
from PIL import Image

model = tf.keras.models.load_model('cnn_best_model.h5')  # Upload this file manually in Colab
 
class_names = ['glioma', 'meningioma', 'no_tumor', 'pituitary']
 
st.set_page_config(page_title="Brain Tumor Classifier", layout="centered")
st.title("Brain Tumor MRI Classifier")
st.markdown("Upload a brain MRI image and get the predicted tumor type.")
 
uploaded_file = st.file_uploader("Upload an MRI image...", type=["jpg", "jpeg", "png"])
 
if uploaded_file is not None:
  image = Image.open(uploaded_file).convert("RGB")
  st.image(image, caption="Uploaded Image", use_column_width=True)
 
  image = image.resize((224, 224))
  image_array = img_to_array(image)
  image_array = np.expand_dims(image_array, axis=0) / 255.0
 
  prediction = model.predict(image_array)
  predicted_class = class_names[np.argmax(prediction)]
 
  st.success(f"Prediction: **{predicted_class.upper()}**")
